version: '{build}'
os: Visual Studio 2017
configuration: Release
environment:
  VisualStudioVersion: 15.0
before_build:
- ps: dotnet restore src
build_script:
- ps: >-
    dotnet build src /nologo

    dotnet pack src --no-build /nologo
test_script:
- ps: dotnet test .\src\Xunit.Combinatorial.Tests\Xunit.Combinatorial.Tests.csproj --no-build
artifacts:
- path: bin\**\*.nupkg
