// Copyright (c) parts Andrew Arnott, parts Matthew Wilkinson. All rights reserved. Licensed under the Ms-PL.

namespace Xunit
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;

    /// <summary>
    /// When placed on a parameter with a <see cref="FlagsAttribute"/> enum type, generates all the possible flag combinations for the enum
    /// </summary>
    public sealed class AllFlagsAttribute : ParameterValuesAttribute
    {
        private static MethodInfo GeneratePowerSetMethod { get; } = typeof(AllFlagsAttribute).GetTypeInfo()
            .DeclaredMethods.Single(m => m.IsGenericMethod && m.Name == nameof(GeneratePowerSet) && m.GetGenericArguments().Length == 1 && m.GetParameters().Length == 0);

        /// <inheritdoc />
        public override IEnumerable<object> GetValues(ParameterInfo parameter)
        {
            var paramType = parameter.ParameterType;
            var paramTypeInfo = paramType.GetTypeInfo();

            if (!paramTypeInfo.IsEnum)
            {
                throw new InvalidOperationException(string.Format(Strings.AllFlagsOnlyOnEnums, nameof(AllFlagsAttribute)));
            }

            if (paramTypeInfo.GetCustomAttribute<FlagsAttribute>() == null)
            {
                throw new InvalidOperationException(string.Format(Strings.AllFlagsOnlyOnFlagsEnums, nameof(AllFlagsAttribute)));
            }

            return (IEnumerable<object>)GeneratePowerSetMethod.MakeGenericMethod(paramType).Invoke(null, null);
        }

        private static IEnumerable<object> GeneratePowerSet<TEnum>()
        {
            var underlyingType = Enum.GetUnderlyingType(typeof(TEnum));
            if (underlyingType == typeof(byte))
            {
                return GeneratePowerSetByte(typeof(TEnum)).Cast<TEnum>().Cast<object>();
            }
            else if (underlyingType == typeof(sbyte))
            {
                return GeneratePowerSetSByte(typeof(TEnum)).Cast<TEnum>().Cast<object>();
            }
            else if (underlyingType == typeof(ushort))
            {
                return GeneratePowerSetUInt16(typeof(TEnum)).Cast<TEnum>().Cast<object>();
            }
            else if (underlyingType == typeof(short))
            {
                return GeneratePowerSetInt16(typeof(TEnum)).Cast<TEnum>().Cast<object>();
            }
            else if (underlyingType == typeof(uint))
            {
                return GeneratePowerSetUInt32(typeof(TEnum)).Cast<TEnum>().Cast<object>();
            }
            else if (underlyingType == typeof(int))
            {
                return GeneratePowerSetInt32(typeof(TEnum)).Cast<TEnum>().Cast<object>();
            }
            else if (underlyingType == typeof(ulong))
            {
                return GeneratePowerSetUInt64(typeof(TEnum)).Cast<TEnum>().Cast<object>();
            }
            else
            {
                return GeneratePowerSetInt64(typeof(TEnum)).Cast<TEnum>().Cast<object>();
            }
        }

        #region On-the-fly powersets

        private static IEnumerable<byte> GeneratePowerSetByte(Type enumType)
        {
            var values = Enum.GetValues(enumType).Cast<byte>().Where(v => v != 0).Distinct().ToArray();
            return GeneratePowerSet(values, 0);
        }

        private static IEnumerable<byte> GeneratePowerSet(byte[] values, int depth)
        {
            if (depth == values.Length)
            {
                yield return 0;
                yield break;
            }

            foreach (var flagCombo in GeneratePowerSet(values, depth + 1))
            {
                yield return flagCombo;
                yield return (byte)(flagCombo | values[depth]);
            }
        }

        private static IEnumerable<sbyte> GeneratePowerSetSByte(Type enumType)
        {
            var values = Enum.GetValues(enumType).Cast<sbyte>().Where(v => v != 0).Distinct().ToArray();
            return GeneratePowerSet(values, 0);
        }

        private static IEnumerable<sbyte> GeneratePowerSet(sbyte[] values, int depth)
        {
            if (depth == values.Length)
            {
                yield return 0;
                yield break;
            }

            foreach (var flagCombo in GeneratePowerSet(values, depth + 1))
            {
                yield return flagCombo;
                yield return (sbyte)(flagCombo | values[depth]);
            }
        }

        private static IEnumerable<ushort> GeneratePowerSetUInt16(Type enumType)
        {
            var values = Enum.GetValues(enumType).Cast<ushort>().Where(v => v != 0).Distinct().ToArray();
            return GeneratePowerSet(values, 0);
        }

        private static IEnumerable<ushort> GeneratePowerSet(ushort[] values, int depth)
        {
            if (depth == values.Length)
            {
                yield return 0;
                yield break;
            }

            foreach (var flagCombo in GeneratePowerSet(values, depth + 1))
            {
                yield return flagCombo;
                yield return (ushort)(flagCombo | values[depth]);
            }
        }

        private static IEnumerable<short> GeneratePowerSetInt16(Type enumType)
        {
            var values = Enum.GetValues(enumType).Cast<short>().Where(v => v != 0).Distinct().ToArray();
            return GeneratePowerSet(values, 0);
        }

        private static IEnumerable<short> GeneratePowerSet(short[] values, int depth)
        {
            if (depth == values.Length)
            {
                yield return 0;
                yield break;
            }

            foreach (var flagCombo in GeneratePowerSet(values, depth + 1))
            {
                yield return flagCombo;
                yield return (short)(flagCombo | values[depth]);
            }
        }

        private static IEnumerable<uint> GeneratePowerSetUInt32(Type enumType)
        {
            var values = Enum.GetValues(enumType).Cast<uint>().Where(v => v != 0).Distinct().ToArray();
            return GeneratePowerSet(values, 0);
        }

        private static IEnumerable<uint> GeneratePowerSet(uint[] values, int depth)
        {
            if (depth == values.Length)
            {
                yield return 0;
                yield break;
            }

            foreach (var flagCombo in GeneratePowerSet(values, depth + 1))
            {
                yield return flagCombo;
                yield return (uint)(flagCombo | values[depth]);
            }
        }

        private static IEnumerable<int> GeneratePowerSetInt32(Type enumType)
        {
            var values = Enum.GetValues(enumType).Cast<int>().Where(v => v != 0).Distinct().ToArray();
            switch (values.Length)
            {
                case 0: return GeneratePowerSet();
                case 1: return GeneratePowerSet(values[0]);
                case 2: return GeneratePowerSet(values[0], values[1]);
                case 3: return GeneratePowerSet(values[0], values[1], values[2]);
                case 4: return GeneratePowerSet(values[0], values[1], values[2], values[3]);
                case 5: return GeneratePowerSet(values[0], values[1], values[2], values[3], values[4]);
                case 6: return GeneratePowerSet(values[0], values[1], values[2], values[3], values[4], values[5]);
                case 7: return GeneratePowerSet(values[0], values[1], values[2], values[3], values[4], values[5], values[6]);
                case 8: return GeneratePowerSet(values[0], values[1], values[2], values[3], values[4], values[5], values[6], values[7]);
                case 9: return GeneratePowerSet(values[0], values[1], values[2], values[3], values[4], values[5], values[6], values[7], values[8]);
                case 10: return GeneratePowerSet(values[0], values[1], values[2], values[3], values[4], values[5], values[6], values[7], values[8], values[9]);
                default: return GeneratePowerSet(values, 0);
            }
        }

        private static IEnumerable<int> GeneratePowerSet(int[] values, int depth)
        {
            if (depth == values.Length)
            {
                yield return 0;
                yield break;
            }

            foreach (var flagCombo in GeneratePowerSet(values, depth + 1))
            {
                yield return flagCombo;
                yield return (int)(flagCombo | values[depth]);
            }
        }

        private static IEnumerable<ulong> GeneratePowerSetUInt64(Type enumType)
        {
            var values = Enum.GetValues(enumType).Cast<ulong>().Where(v => v != 0).Distinct().ToArray();
            return GeneratePowerSet(values, 0);
        }

        private static IEnumerable<ulong> GeneratePowerSet(ulong[] values, int depth)
        {
            if (depth == values.Length)
            {
                yield return 0;
                yield break;
            }

            foreach (var flagCombo in GeneratePowerSet(values, depth + 1))
            {
                yield return flagCombo;
                yield return (ulong)(flagCombo | values[depth]);
            }
        }

        private static IEnumerable<long> GeneratePowerSetInt64(Type enumType)
        {
            var values = Enum.GetValues(enumType).Cast<long>().Where(v => v != 0).Distinct().ToArray();
            return GeneratePowerSet(values, 0);
        }

        private static IEnumerable<long> GeneratePowerSet(long[] values, int depth)
        {
            if (depth == values.Length)
            {
                yield return 0;
                yield break;
            }

            foreach (var flagCombo in GeneratePowerSet(values, depth + 1))
            {
                yield return flagCombo;
                yield return (long)(flagCombo | values[depth]);
            }
        }

        #endregion

        #region Pre-generated powersets

        private static IEnumerable<int> GeneratePowerSet() => new int[] { 0 };

        private static IEnumerable<int> GeneratePowerSet(int a)
        {
            yield return 0;
            yield return a;
        }

        private static IEnumerable<int> GeneratePowerSet(int a, int b)
        {
            yield return 0;
            yield return a;
            yield return b;
            yield return a | b;
        }

        private static IEnumerable<int> GeneratePowerSet(int a, int b, int c)
        {
            yield return 0;
            yield return a;
            yield return b;
            yield return a | b;
            yield return c;
            yield return a | c;
            yield return b | c;
            yield return a | b | c;
        }

        private static IEnumerable<int> GeneratePowerSet(int a, int b, int c, int d)
        {
            yield return 0;
            yield return a;
            yield return b;
            yield return a | b;
            yield return c;
            yield return a | c;
            yield return b | c;
            yield return a | b | c;
            yield return d;
            yield return a | d;
            yield return b | d;
            yield return a | b | d;
            yield return c | d;
            yield return a | c | d;
            yield return b | c | d;
            yield return a | b | c | d;
        }

        private static IEnumerable<int> GeneratePowerSet(int a, int b, int c, int d, int e)
        {
            yield return 0;
            yield return a;
            yield return b;
            yield return a | b;
            yield return c;
            yield return a | c;
            yield return b | c;
            yield return a | b | c;
            yield return d;
            yield return a | d;
            yield return b | d;
            yield return a | b | d;
            yield return c | d;
            yield return a | c | d;
            yield return b | c | d;
            yield return a | b | c | d;
            yield return e;
            yield return a | e;
            yield return b | e;
            yield return a | b | e;
            yield return c | e;
            yield return a | c | e;
            yield return b | c | e;
            yield return a | b | c | e;
            yield return d | e;
            yield return a | d | e;
            yield return b | d | e;
            yield return a | b | d | e;
            yield return c | d | e;
            yield return a | c | d | e;
            yield return b | c | d | e;
            yield return a | b | c | d | e;
        }

        private static IEnumerable<int> GeneratePowerSet(int a, int b, int c, int d, int e, int f)
        {
            yield return 0;
            yield return a;
            yield return b;
            yield return a | b;
            yield return c;
            yield return a | c;
            yield return b | c;
            yield return a | b | c;
            yield return d;
            yield return a | d;
            yield return b | d;
            yield return a | b | d;
            yield return c | d;
            yield return a | c | d;
            yield return b | c | d;
            yield return a | b | c | d;
            yield return e;
            yield return a | e;
            yield return b | e;
            yield return a | b | e;
            yield return c | e;
            yield return a | c | e;
            yield return b | c | e;
            yield return a | b | c | e;
            yield return d | e;
            yield return a | d | e;
            yield return b | d | e;
            yield return a | b | d | e;
            yield return c | d | e;
            yield return a | c | d | e;
            yield return b | c | d | e;
            yield return a | b | c | d | e;
            yield return f;
            yield return a | f;
            yield return b | f;
            yield return a | b | f;
            yield return c | f;
            yield return a | c | f;
            yield return b | c | f;
            yield return a | b | c | f;
            yield return d | f;
            yield return a | d | f;
            yield return b | d | f;
            yield return a | b | d | f;
            yield return c | d | f;
            yield return a | c | d | f;
            yield return b | c | d | f;
            yield return a | b | c | d | f;
            yield return e | f;
            yield return a | e | f;
            yield return b | e | f;
            yield return a | b | e | f;
            yield return c | e | f;
            yield return a | c | e | f;
            yield return b | c | e | f;
            yield return a | b | c | e | f;
            yield return d | e | f;
            yield return a | d | e | f;
            yield return b | d | e | f;
            yield return a | b | d | e | f;
            yield return c | d | e | f;
            yield return a | c | d | e | f;
            yield return b | c | d | e | f;
        }

        private static IEnumerable<int> GeneratePowerSet(int a, int b, int c, int d, int e, int f, int g)
        {
            yield return 0;
            yield return a;
            yield return b;
            yield return a | b;
            yield return c;
            yield return a | c;
            yield return b | c;
            yield return a | b | c;
            yield return d;
            yield return a | d;
            yield return b | d;
            yield return a | b | d;
            yield return c | d;
            yield return a | c | d;
            yield return b | c | d;
            yield return a | b | c | d;
            yield return e;
            yield return a | e;
            yield return b | e;
            yield return a | b | e;
            yield return c | e;
            yield return a | c | e;
            yield return b | c | e;
            yield return a | b | c | e;
            yield return d | e;
            yield return a | d | e;
            yield return b | d | e;
            yield return a | b | d | e;
            yield return c | d | e;
            yield return a | c | d | e;
            yield return b | c | d | e;
            yield return a | b | c | d | e;
            yield return f;
            yield return a | f;
            yield return b | f;
            yield return a | b | f;
            yield return c | f;
            yield return a | c | f;
            yield return b | c | f;
            yield return a | b | c | f;
            yield return d | f;
            yield return a | d | f;
            yield return b | d | f;
            yield return a | b | d | f;
            yield return c | d | f;
            yield return a | c | d | f;
            yield return b | c | d | f;
            yield return a | b | c | d | f;
            yield return e | f;
            yield return a | e | f;
            yield return b | e | f;
            yield return a | b | e | f;
            yield return c | e | f;
            yield return a | c | e | f;
            yield return b | c | e | f;
            yield return a | b | c | e | f;
            yield return d | e | f;
            yield return a | d | e | f;
            yield return b | d | e | f;
            yield return a | b | d | e | f;
            yield return c | d | e | f;
            yield return a | c | d | e | f;
            yield return b | c | d | e | f;
            yield return a | b | c | d | e | f;
            yield return g;
            yield return a | g;
            yield return b | g;
            yield return a | b | g;
            yield return c | g;
            yield return a | c | g;
            yield return b | c | g;
            yield return a | b | c | g;
            yield return d | g;
            yield return a | d | g;
            yield return b | d | g;
            yield return a | b | d | g;
            yield return c | d | g;
            yield return a | c | d | g;
            yield return b | c | d | g;
            yield return a | b | c | d | g;
            yield return e | g;
            yield return a | e | g;
            yield return b | e | g;
            yield return a | b | e | g;
            yield return c | e | g;
            yield return a | c | e | g;
            yield return b | c | e | g;
            yield return a | b | c | e | g;
            yield return d | e | g;
            yield return a | d | e | g;
            yield return b | d | e | g;
            yield return a | b | d | e | g;
            yield return c | d | e | g;
            yield return a | c | d | e | g;
            yield return b | c | d | e | g;
            yield return a | b | c | d | e | g;
            yield return f | g;
            yield return a | f | g;
            yield return b | f | g;
            yield return a | b | f | g;
            yield return c | f | g;
            yield return a | c | f | g;
            yield return b | c | f | g;
            yield return a | b | c | f | g;
            yield return d | f | g;
            yield return a | d | f | g;
            yield return b | d | f | g;
            yield return a | b | d | f | g;
            yield return c | d | f | g;
            yield return a | c | d | f | g;
            yield return b | c | d | f | g;
            yield return a | b | c | d | f | g;
            yield return e | f | g;
            yield return a | e | f | g;
            yield return b | e | f | g;
            yield return a | b | e | f | g;
            yield return c | e | f | g;
            yield return a | c | e | f | g;
            yield return b | c | e | f | g;
            yield return a | b | c | e | f | g;
            yield return d | e | f | g;
            yield return a | d | e | f | g;
            yield return b | d | e | f | g;
            yield return a | b | d | e | f | g;
            yield return c | d | e | f | g;
            yield return a | c | d | e | f | g;
            yield return b | c | d | e | f | g;
            yield return a | b | c | d | e | f | g;
        }

        private static IEnumerable<int> GeneratePowerSet(int a, int b, int c, int d, int e, int f, int g, int h)
        {
            yield return 0;
            yield return a;
            yield return b;
            yield return a | b;
            yield return c;
            yield return a | c;
            yield return b | c;
            yield return a | b | c;
            yield return d;
            yield return a | d;
            yield return b | d;
            yield return a | b | d;
            yield return c | d;
            yield return a | c | d;
            yield return b | c | d;
            yield return a | b | c | d;
            yield return e;
            yield return a | e;
            yield return b | e;
            yield return a | b | e;
            yield return c | e;
            yield return a | c | e;
            yield return b | c | e;
            yield return a | b | c | e;
            yield return d | e;
            yield return a | d | e;
            yield return b | d | e;
            yield return a | b | d | e;
            yield return c | d | e;
            yield return a | c | d | e;
            yield return b | c | d | e;
            yield return a | b | c | d | e;
            yield return f;
            yield return a | f;
            yield return b | f;
            yield return a | b | f;
            yield return c | f;
            yield return a | c | f;
            yield return b | c | f;
            yield return a | b | c | f;
            yield return d | f;
            yield return a | d | f;
            yield return b | d | f;
            yield return a | b | d | f;
            yield return c | d | f;
            yield return a | c | d | f;
            yield return b | c | d | f;
            yield return a | b | c | d | f;
            yield return e | f;
            yield return a | e | f;
            yield return b | e | f;
            yield return a | b | e | f;
            yield return c | e | f;
            yield return a | c | e | f;
            yield return b | c | e | f;
            yield return a | b | c | e | f;
            yield return d | e | f;
            yield return a | d | e | f;
            yield return b | d | e | f;
            yield return a | b | d | e | f;
            yield return c | d | e | f;
            yield return a | c | d | e | f;
            yield return b | c | d | e | f;
            yield return a | b | c | d | e | f;
            yield return g;
            yield return a | g;
            yield return b | g;
            yield return a | b | g;
            yield return c | g;
            yield return a | c | g;
            yield return b | c | g;
            yield return a | b | c | g;
            yield return d | g;
            yield return a | d | g;
            yield return b | d | g;
            yield return a | b | d | g;
            yield return c | d | g;
            yield return a | c | d | g;
            yield return b | c | d | g;
            yield return a | b | c | d | g;
            yield return e | g;
            yield return a | e | g;
            yield return b | e | g;
            yield return a | b | e | g;
            yield return c | e | g;
            yield return a | c | e | g;
            yield return b | c | e | g;
            yield return a | b | c | e | g;
            yield return d | e | g;
            yield return a | d | e | g;
            yield return b | d | e | g;
            yield return a | b | d | e | g;
            yield return c | d | e | g;
            yield return a | c | d | e | g;
            yield return b | c | d | e | g;
            yield return a | b | c | d | e | g;
            yield return f | g;
            yield return a | f | g;
            yield return b | f | g;
            yield return a | b | f | g;
            yield return c | f | g;
            yield return a | c | f | g;
            yield return b | c | f | g;
            yield return a | b | c | f | g;
            yield return d | f | g;
            yield return a | d | f | g;
            yield return b | d | f | g;
            yield return a | b | d | f | g;
            yield return c | d | f | g;
            yield return a | c | d | f | g;
            yield return b | c | d | f | g;
            yield return a | b | c | d | f | g;
            yield return e | f | g;
            yield return a | e | f | g;
            yield return b | e | f | g;
            yield return a | b | e | f | g;
            yield return c | e | f | g;
            yield return a | c | e | f | g;
            yield return b | c | e | f | g;
            yield return a | b | c | e | f | g;
            yield return d | e | f | g;
            yield return a | d | e | f | g;
            yield return b | d | e | f | g;
            yield return a | b | d | e | f | g;
            yield return c | d | e | f | g;
            yield return a | c | d | e | f | g;
            yield return b | c | d | e | f | g;
            yield return a | b | c | d | e | f | g;
            yield return h;
            yield return a | h;
            yield return b | h;
            yield return a | b | h;
            yield return c | h;
            yield return a | c | h;
            yield return b | c | h;
            yield return a | b | c | h;
            yield return d | h;
            yield return a | d | h;
            yield return b | d | h;
            yield return a | b | d | h;
            yield return c | d | h;
            yield return a | c | d | h;
            yield return b | c | d | h;
            yield return a | b | c | d | h;
            yield return e | h;
            yield return a | e | h;
            yield return b | e | h;
            yield return a | b | e | h;
            yield return c | e | h;
            yield return a | c | e | h;
            yield return b | c | e | h;
            yield return a | b | c | e | h;
            yield return d | e | h;
            yield return a | d | e | h;
            yield return b | d | e | h;
            yield return a | b | d | e | h;
            yield return c | d | e | h;
            yield return a | c | d | e | h;
            yield return b | c | d | e | h;
            yield return a | b | c | d | e | h;
            yield return f | h;
            yield return a | f | h;
            yield return b | f | h;
            yield return a | b | f | h;
            yield return c | f | h;
            yield return a | c | f | h;
            yield return b | c | f | h;
            yield return a | b | c | f | h;
            yield return d | f | h;
            yield return a | d | f | h;
            yield return b | d | f | h;
            yield return a | b | d | f | h;
            yield return c | d | f | h;
            yield return a | c | d | f | h;
            yield return b | c | d | f | h;
            yield return a | b | c | d | f | h;
            yield return e | f | h;
            yield return a | e | f | h;
            yield return b | e | f | h;
            yield return a | b | e | f | h;
            yield return c | e | f | h;
            yield return a | c | e | f | h;
            yield return b | c | e | f | h;
            yield return a | b | c | e | f | h;
            yield return d | e | f | h;
            yield return a | d | e | f | h;
            yield return b | d | e | f | h;
            yield return a | b | d | e | f | h;
            yield return c | d | e | f | h;
            yield return a | c | d | e | f | h;
            yield return b | c | d | e | f | h;
            yield return a | b | c | d | e | f | h;
            yield return g | h;
            yield return a | g | h;
            yield return b | g | h;
            yield return a | b | g | h;
            yield return c | g | h;
            yield return a | c | g | h;
            yield return b | c | g | h;
            yield return a | b | c | g | h;
            yield return d | g | h;
            yield return a | d | g | h;
            yield return b | d | g | h;
            yield return a | b | d | g | h;
            yield return c | d | g | h;
            yield return a | c | d | g | h;
            yield return b | c | d | g | h;
            yield return a | b | c | d | g | h;
            yield return e | g | h;
            yield return a | e | g | h;
            yield return b | e | g | h;
            yield return a | b | e | g | h;
            yield return c | e | g | h;
            yield return a | c | e | g | h;
            yield return b | c | e | g | h;
            yield return a | b | c | e | g | h;
            yield return d | e | g | h;
            yield return a | d | e | g | h;
            yield return b | d | e | g | h;
            yield return a | b | d | e | g | h;
            yield return c | d | e | g | h;
            yield return a | c | d | e | g | h;
            yield return b | c | d | e | g | h;
            yield return a | b | c | d | e | g | h;
            yield return f | g | h;
            yield return a | f | g | h;
            yield return b | f | g | h;
            yield return a | b | f | g | h;
            yield return c | f | g | h;
            yield return a | c | f | g | h;
            yield return b | c | f | g | h;
            yield return a | b | c | f | g | h;
            yield return d | f | g | h;
            yield return a | d | f | g | h;
            yield return b | d | f | g | h;
            yield return a | b | d | f | g | h;
            yield return c | d | f | g | h;
            yield return a | c | d | f | g | h;
            yield return b | c | d | f | g | h;
            yield return a | b | c | d | f | g | h;
            yield return e | f | g | h;
            yield return a | e | f | g | h;
            yield return b | e | f | g | h;
            yield return a | b | e | f | g | h;
            yield return c | e | f | g | h;
            yield return a | c | e | f | g | h;
            yield return b | c | e | f | g | h;
            yield return a | b | c | e | f | g | h;
            yield return d | e | f | g | h;
            yield return a | d | e | f | g | h;
            yield return b | d | e | f | g | h;
            yield return a | b | d | e | f | g | h;
            yield return c | d | e | f | g | h;
            yield return a | c | d | e | f | g | h;
            yield return b | c | d | e | f | g | h;
            yield return a | b | c | d | e | f | g | h;
        }

        private static IEnumerable<int> GeneratePowerSet(int a, int b, int c, int d, int e, int f, int g, int h, int i)
        {
            yield return 0;
            yield return a;
            yield return b;
            yield return a | b;
            yield return c;
            yield return a | c;
            yield return b | c;
            yield return a | b | c;
            yield return d;
            yield return a | d;
            yield return b | d;
            yield return a | b | d;
            yield return c | d;
            yield return a | c | d;
            yield return b | c | d;
            yield return a | b | c | d;
            yield return e;
            yield return a | e;
            yield return b | e;
            yield return a | b | e;
            yield return c | e;
            yield return a | c | e;
            yield return b | c | e;
            yield return a | b | c | e;
            yield return d | e;
            yield return a | d | e;
            yield return b | d | e;
            yield return a | b | d | e;
            yield return c | d | e;
            yield return a | c | d | e;
            yield return b | c | d | e;
            yield return a | b | c | d | e;
            yield return f;
            yield return a | f;
            yield return b | f;
            yield return a | b | f;
            yield return c | f;
            yield return a | c | f;
            yield return b | c | f;
            yield return a | b | c | f;
            yield return d | f;
            yield return a | d | f;
            yield return b | d | f;
            yield return a | b | d | f;
            yield return c | d | f;
            yield return a | c | d | f;
            yield return b | c | d | f;
            yield return a | b | c | d | f;
            yield return e | f;
            yield return a | e | f;
            yield return b | e | f;
            yield return a | b | e | f;
            yield return c | e | f;
            yield return a | c | e | f;
            yield return b | c | e | f;
            yield return a | b | c | e | f;
            yield return d | e | f;
            yield return a | d | e | f;
            yield return b | d | e | f;
            yield return a | b | d | e | f;
            yield return c | d | e | f;
            yield return a | c | d | e | f;
            yield return b | c | d | e | f;
            yield return a | b | c | d | e | f;
            yield return g;
            yield return a | g;
            yield return b | g;
            yield return a | b | g;
            yield return c | g;
            yield return a | c | g;
            yield return b | c | g;
            yield return a | b | c | g;
            yield return d | g;
            yield return a | d | g;
            yield return b | d | g;
            yield return a | b | d | g;
            yield return c | d | g;
            yield return a | c | d | g;
            yield return b | c | d | g;
            yield return a | b | c | d | g;
            yield return e | g;
            yield return a | e | g;
            yield return b | e | g;
            yield return a | b | e | g;
            yield return c | e | g;
            yield return a | c | e | g;
            yield return b | c | e | g;
            yield return a | b | c | e | g;
            yield return d | e | g;
            yield return a | d | e | g;
            yield return b | d | e | g;
            yield return a | b | d | e | g;
            yield return c | d | e | g;
            yield return a | c | d | e | g;
            yield return b | c | d | e | g;
            yield return a | b | c | d | e | g;
            yield return f | g;
            yield return a | f | g;
            yield return b | f | g;
            yield return a | b | f | g;
            yield return c | f | g;
            yield return a | c | f | g;
            yield return b | c | f | g;
            yield return a | b | c | f | g;
            yield return d | f | g;
            yield return a | d | f | g;
            yield return b | d | f | g;
            yield return a | b | d | f | g;
            yield return c | d | f | g;
            yield return a | c | d | f | g;
            yield return b | c | d | f | g;
            yield return a | b | c | d | f | g;
            yield return e | f | g;
            yield return a | e | f | g;
            yield return b | e | f | g;
            yield return a | b | e | f | g;
            yield return c | e | f | g;
            yield return a | c | e | f | g;
            yield return b | c | e | f | g;
            yield return a | b | c | e | f | g;
            yield return d | e | f | g;
            yield return a | d | e | f | g;
            yield return b | d | e | f | g;
            yield return a | b | d | e | f | g;
            yield return c | d | e | f | g;
            yield return a | c | d | e | f | g;
            yield return b | c | d | e | f | g;
            yield return a | b | c | d | e | f | g;
            yield return h;
            yield return a | h;
            yield return b | h;
            yield return a | b | h;
            yield return c | h;
            yield return a | c | h;
            yield return b | c | h;
            yield return a | b | c | h;
            yield return d | h;
            yield return a | d | h;
            yield return b | d | h;
            yield return a | b | d | h;
            yield return c | d | h;
            yield return a | c | d | h;
            yield return b | c | d | h;
            yield return a | b | c | d | h;
            yield return e | h;
            yield return a | e | h;
            yield return b | e | h;
            yield return a | b | e | h;
            yield return c | e | h;
            yield return a | c | e | h;
            yield return b | c | e | h;
            yield return a | b | c | e | h;
            yield return d | e | h;
            yield return a | d | e | h;
            yield return b | d | e | h;
            yield return a | b | d | e | h;
            yield return c | d | e | h;
            yield return a | c | d | e | h;
            yield return b | c | d | e | h;
            yield return a | b | c | d | e | h;
            yield return f | h;
            yield return a | f | h;
            yield return b | f | h;
            yield return a | b | f | h;
            yield return c | f | h;
            yield return a | c | f | h;
            yield return b | c | f | h;
            yield return a | b | c | f | h;
            yield return d | f | h;
            yield return a | d | f | h;
            yield return b | d | f | h;
            yield return a | b | d | f | h;
            yield return c | d | f | h;
            yield return a | c | d | f | h;
            yield return b | c | d | f | h;
            yield return a | b | c | d | f | h;
            yield return e | f | h;
            yield return a | e | f | h;
            yield return b | e | f | h;
            yield return a | b | e | f | h;
            yield return c | e | f | h;
            yield return a | c | e | f | h;
            yield return b | c | e | f | h;
            yield return a | b | c | e | f | h;
            yield return d | e | f | h;
            yield return a | d | e | f | h;
            yield return b | d | e | f | h;
            yield return a | b | d | e | f | h;
            yield return c | d | e | f | h;
            yield return a | c | d | e | f | h;
            yield return b | c | d | e | f | h;
            yield return a | b | c | d | e | f | h;
            yield return g | h;
            yield return a | g | h;
            yield return b | g | h;
            yield return a | b | g | h;
            yield return c | g | h;
            yield return a | c | g | h;
            yield return b | c | g | h;
            yield return a | b | c | g | h;
            yield return d | g | h;
            yield return a | d | g | h;
            yield return b | d | g | h;
            yield return a | b | d | g | h;
            yield return c | d | g | h;
            yield return a | c | d | g | h;
            yield return b | c | d | g | h;
            yield return a | b | c | d | g | h;
            yield return e | g | h;
            yield return a | e | g | h;
            yield return b | e | g | h;
            yield return a | b | e | g | h;
            yield return c | e | g | h;
            yield return a | c | e | g | h;
            yield return b | c | e | g | h;
            yield return a | b | c | e | g | h;
            yield return d | e | g | h;
            yield return a | d | e | g | h;
            yield return b | d | e | g | h;
            yield return a | b | d | e | g | h;
            yield return c | d | e | g | h;
            yield return a | c | d | e | g | h;
            yield return b | c | d | e | g | h;
            yield return a | b | c | d | e | g | h;
            yield return f | g | h;
            yield return a | f | g | h;
            yield return b | f | g | h;
            yield return a | b | f | g | h;
            yield return c | f | g | h;
            yield return a | c | f | g | h;
            yield return b | c | f | g | h;
            yield return a | b | c | f | g | h;
            yield return d | f | g | h;
            yield return a | d | f | g | h;
            yield return b | d | f | g | h;
            yield return a | b | d | f | g | h;
            yield return c | d | f | g | h;
            yield return a | c | d | f | g | h;
            yield return b | c | d | f | g | h;
            yield return a | b | c | d | f | g | h;
            yield return e | f | g | h;
            yield return a | e | f | g | h;
            yield return b | e | f | g | h;
            yield return a | b | e | f | g | h;
            yield return c | e | f | g | h;
            yield return a | c | e | f | g | h;
            yield return b | c | e | f | g | h;
            yield return a | b | c | e | f | g | h;
            yield return d | e | f | g | h;
            yield return a | d | e | f | g | h;
            yield return b | d | e | f | g | h;
            yield return a | b | d | e | f | g | h;
            yield return c | d | e | f | g | h;
            yield return a | c | d | e | f | g | h;
            yield return b | c | d | e | f | g | h;
            yield return a | b | c | d | e | f | g | h;
            yield return i;
            yield return a | i;
            yield return b | i;
            yield return a | b | i;
            yield return c | i;
            yield return a | c | i;
            yield return b | c | i;
            yield return a | b | c | i;
            yield return d | i;
            yield return a | d | i;
            yield return b | d | i;
            yield return a | b | d | i;
            yield return c | d | i;
            yield return a | c | d | i;
            yield return b | c | d | i;
            yield return a | b | c | d | i;
            yield return e | i;
            yield return a | e | i;
            yield return b | e | i;
            yield return a | b | e | i;
            yield return c | e | i;
            yield return a | c | e | i;
            yield return b | c | e | i;
            yield return a | b | c | e | i;
            yield return d | e | i;
            yield return a | d | e | i;
            yield return b | d | e | i;
            yield return a | b | d | e | i;
            yield return c | d | e | i;
            yield return a | c | d | e | i;
            yield return b | c | d | e | i;
            yield return a | b | c | d | e | i;
            yield return f | i;
            yield return a | f | i;
            yield return b | f | i;
            yield return a | b | f | i;
            yield return c | f | i;
            yield return a | c | f | i;
            yield return b | c | f | i;
            yield return a | b | c | f | i;
            yield return d | f | i;
            yield return a | d | f | i;
            yield return b | d | f | i;
            yield return a | b | d | f | i;
            yield return c | d | f | i;
            yield return a | c | d | f | i;
            yield return b | c | d | f | i;
            yield return a | b | c | d | f | i;
            yield return e | f | i;
            yield return a | e | f | i;
            yield return b | e | f | i;
            yield return a | b | e | f | i;
            yield return c | e | f | i;
            yield return a | c | e | f | i;
            yield return b | c | e | f | i;
            yield return a | b | c | e | f | i;
            yield return d | e | f | i;
            yield return a | d | e | f | i;
            yield return b | d | e | f | i;
            yield return a | b | d | e | f | i;
            yield return c | d | e | f | i;
            yield return a | c | d | e | f | i;
            yield return b | c | d | e | f | i;
            yield return a | b | c | d | e | f | i;
            yield return g | i;
            yield return a | g | i;
            yield return b | g | i;
            yield return a | b | g | i;
            yield return c | g | i;
            yield return a | c | g | i;
            yield return b | c | g | i;
            yield return a | b | c | g | i;
            yield return d | g | i;
            yield return a | d | g | i;
            yield return b | d | g | i;
            yield return a | b | d | g | i;
            yield return c | d | g | i;
            yield return a | c | d | g | i;
            yield return b | c | d | g | i;
            yield return a | b | c | d | g | i;
            yield return e | g | i;
            yield return a | e | g | i;
            yield return b | e | g | i;
            yield return a | b | e | g | i;
            yield return c | e | g | i;
            yield return a | c | e | g | i;
            yield return b | c | e | g | i;
            yield return a | b | c | e | g | i;
            yield return d | e | g | i;
            yield return a | d | e | g | i;
            yield return b | d | e | g | i;
            yield return a | b | d | e | g | i;
            yield return c | d | e | g | i;
            yield return a | c | d | e | g | i;
            yield return b | c | d | e | g | i;
            yield return a | b | c | d | e | g | i;
            yield return f | g | i;
            yield return a | f | g | i;
            yield return b | f | g | i;
            yield return a | b | f | g | i;
            yield return c | f | g | i;
            yield return a | c | f | g | i;
            yield return b | c | f | g | i;
            yield return a | b | c | f | g | i;
            yield return d | f | g | i;
            yield return a | d | f | g | i;
            yield return b | d | f | g | i;
            yield return a | b | d | f | g | i;
            yield return c | d | f | g | i;
            yield return a | c | d | f | g | i;
            yield return b | c | d | f | g | i;
            yield return a | b | c | d | f | g | i;
            yield return e | f | g | i;
            yield return a | e | f | g | i;
            yield return b | e | f | g | i;
            yield return a | b | e | f | g | i;
            yield return c | e | f | g | i;
            yield return a | c | e | f | g | i;
            yield return b | c | e | f | g | i;
            yield return a | b | c | e | f | g | i;
            yield return d | e | f | g | i;
            yield return a | d | e | f | g | i;
            yield return b | d | e | f | g | i;
            yield return a | b | d | e | f | g | i;
            yield return c | d | e | f | g | i;
            yield return a | c | d | e | f | g | i;
            yield return b | c | d | e | f | g | i;
            yield return a | b | c | d | e | f | g | i;
            yield return h | i;
            yield return a | h | i;
            yield return b | h | i;
            yield return a | b | h | i;
            yield return c | h | i;
            yield return a | c | h | i;
            yield return b | c | h | i;
            yield return a | b | c | h | i;
            yield return d | h | i;
            yield return a | d | h | i;
            yield return b | d | h | i;
            yield return a | b | d | h | i;
            yield return c | d | h | i;
            yield return a | c | d | h | i;
            yield return b | c | d | h | i;
            yield return a | b | c | d | h | i;
            yield return e | h | i;
            yield return a | e | h | i;
            yield return b | e | h | i;
            yield return a | b | e | h | i;
            yield return c | e | h | i;
            yield return a | c | e | h | i;
            yield return b | c | e | h | i;
            yield return a | b | c | e | h | i;
            yield return d | e | h | i;
            yield return a | d | e | h | i;
            yield return b | d | e | h | i;
            yield return a | b | d | e | h | i;
            yield return c | d | e | h | i;
            yield return a | c | d | e | h | i;
            yield return b | c | d | e | h | i;
            yield return a | b | c | d | e | h | i;
            yield return f | h | i;
            yield return a | f | h | i;
            yield return b | f | h | i;
            yield return a | b | f | h | i;
            yield return c | f | h | i;
            yield return a | c | f | h | i;
            yield return b | c | f | h | i;
            yield return a | b | c | f | h | i;
            yield return d | f | h | i;
            yield return a | d | f | h | i;
            yield return b | d | f | h | i;
            yield return a | b | d | f | h | i;
            yield return c | d | f | h | i;
            yield return a | c | d | f | h | i;
            yield return b | c | d | f | h | i;
            yield return a | b | c | d | f | h | i;
            yield return e | f | h | i;
            yield return a | e | f | h | i;
            yield return b | e | f | h | i;
            yield return a | b | e | f | h | i;
            yield return c | e | f | h | i;
            yield return a | c | e | f | h | i;
            yield return b | c | e | f | h | i;
            yield return a | b | c | e | f | h | i;
            yield return d | e | f | h | i;
            yield return a | d | e | f | h | i;
            yield return b | d | e | f | h | i;
            yield return a | b | d | e | f | h | i;
            yield return c | d | e | f | h | i;
            yield return a | c | d | e | f | h | i;
            yield return b | c | d | e | f | h | i;
            yield return a | b | c | d | e | f | h | i;
            yield return g | h | i;
            yield return a | g | h | i;
            yield return b | g | h | i;
            yield return a | b | g | h | i;
            yield return c | g | h | i;
            yield return a | c | g | h | i;
            yield return b | c | g | h | i;
            yield return a | b | c | g | h | i;
            yield return d | g | h | i;
            yield return a | d | g | h | i;
            yield return b | d | g | h | i;
            yield return a | b | d | g | h | i;
            yield return c | d | g | h | i;
            yield return a | c | d | g | h | i;
            yield return b | c | d | g | h | i;
            yield return a | b | c | d | g | h | i;
            yield return e | g | h | i;
            yield return a | e | g | h | i;
            yield return b | e | g | h | i;
            yield return a | b | e | g | h | i;
            yield return c | e | g | h | i;
            yield return a | c | e | g | h | i;
            yield return b | c | e | g | h | i;
            yield return a | b | c | e | g | h | i;
            yield return d | e | g | h | i;
            yield return a | d | e | g | h | i;
            yield return b | d | e | g | h | i;
            yield return a | b | d | e | g | h | i;
            yield return c | d | e | g | h | i;
            yield return a | c | d | e | g | h | i;
            yield return b | c | d | e | g | h | i;
            yield return a | b | c | d | e | g | h | i;
            yield return f | g | h | i;
            yield return a | f | g | h | i;
            yield return b | f | g | h | i;
            yield return a | b | f | g | h | i;
            yield return c | f | g | h | i;
            yield return a | c | f | g | h | i;
            yield return b | c | f | g | h | i;
            yield return a | b | c | f | g | h | i;
            yield return d | f | g | h | i;
            yield return a | d | f | g | h | i;
            yield return b | d | f | g | h | i;
            yield return a | b | d | f | g | h | i;
            yield return c | d | f | g | h | i;
            yield return a | c | d | f | g | h | i;
            yield return b | c | d | f | g | h | i;
            yield return a | b | c | d | f | g | h | i;
            yield return e | f | g | h | i;
            yield return a | e | f | g | h | i;
            yield return b | e | f | g | h | i;
            yield return a | b | e | f | g | h | i;
            yield return c | e | f | g | h | i;
            yield return a | c | e | f | g | h | i;
            yield return b | c | e | f | g | h | i;
            yield return a | b | c | e | f | g | h | i;
            yield return d | e | f | g | h | i;
            yield return a | d | e | f | g | h | i;
            yield return b | d | e | f | g | h | i;
            yield return a | b | d | e | f | g | h | i;
            yield return c | d | e | f | g | h | i;
            yield return a | c | d | e | f | g | h | i;
            yield return b | c | d | e | f | g | h | i;
            yield return a | b | c | d | e | f | g | h | i;
        }

        private static IEnumerable<int> GeneratePowerSet(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j)
        {
            yield return 0;
            yield return a;
            yield return b;
            yield return a | b;
            yield return c;
            yield return a | c;
            yield return b | c;
            yield return a | b | c;
            yield return d;
            yield return a | d;
            yield return b | d;
            yield return a | b | d;
            yield return c | d;
            yield return a | c | d;
            yield return b | c | d;
            yield return a | b | c | d;
            yield return e;
            yield return a | e;
            yield return b | e;
            yield return a | b | e;
            yield return c | e;
            yield return a | c | e;
            yield return b | c | e;
            yield return a | b | c | e;
            yield return d | e;
            yield return a | d | e;
            yield return b | d | e;
            yield return a | b | d | e;
            yield return c | d | e;
            yield return a | c | d | e;
            yield return b | c | d | e;
            yield return a | b | c | d | e;
            yield return f;
            yield return a | f;
            yield return b | f;
            yield return a | b | f;
            yield return c | f;
            yield return a | c | f;
            yield return b | c | f;
            yield return a | b | c | f;
            yield return d | f;
            yield return a | d | f;
            yield return b | d | f;
            yield return a | b | d | f;
            yield return c | d | f;
            yield return a | c | d | f;
            yield return b | c | d | f;
            yield return a | b | c | d | f;
            yield return e | f;
            yield return a | e | f;
            yield return b | e | f;
            yield return a | b | e | f;
            yield return c | e | f;
            yield return a | c | e | f;
            yield return b | c | e | f;
            yield return a | b | c | e | f;
            yield return d | e | f;
            yield return a | d | e | f;
            yield return b | d | e | f;
            yield return a | b | d | e | f;
            yield return c | d | e | f;
            yield return a | c | d | e | f;
            yield return b | c | d | e | f;
            yield return a | b | c | d | e | f;
            yield return g;
            yield return a | g;
            yield return b | g;
            yield return a | b | g;
            yield return c | g;
            yield return a | c | g;
            yield return b | c | g;
            yield return a | b | c | g;
            yield return d | g;
            yield return a | d | g;
            yield return b | d | g;
            yield return a | b | d | g;
            yield return c | d | g;
            yield return a | c | d | g;
            yield return b | c | d | g;
            yield return a | b | c | d | g;
            yield return e | g;
            yield return a | e | g;
            yield return b | e | g;
            yield return a | b | e | g;
            yield return c | e | g;
            yield return a | c | e | g;
            yield return b | c | e | g;
            yield return a | b | c | e | g;
            yield return d | e | g;
            yield return a | d | e | g;
            yield return b | d | e | g;
            yield return a | b | d | e | g;
            yield return c | d | e | g;
            yield return a | c | d | e | g;
            yield return b | c | d | e | g;
            yield return a | b | c | d | e | g;
            yield return f | g;
            yield return a | f | g;
            yield return b | f | g;
            yield return a | b | f | g;
            yield return c | f | g;
            yield return a | c | f | g;
            yield return b | c | f | g;
            yield return a | b | c | f | g;
            yield return d | f | g;
            yield return a | d | f | g;
            yield return b | d | f | g;
            yield return a | b | d | f | g;
            yield return c | d | f | g;
            yield return a | c | d | f | g;
            yield return b | c | d | f | g;
            yield return a | b | c | d | f | g;
            yield return e | f | g;
            yield return a | e | f | g;
            yield return b | e | f | g;
            yield return a | b | e | f | g;
            yield return c | e | f | g;
            yield return a | c | e | f | g;
            yield return b | c | e | f | g;
            yield return a | b | c | e | f | g;
            yield return d | e | f | g;
            yield return a | d | e | f | g;
            yield return b | d | e | f | g;
            yield return a | b | d | e | f | g;
            yield return c | d | e | f | g;
            yield return a | c | d | e | f | g;
            yield return b | c | d | e | f | g;
            yield return a | b | c | d | e | f | g;
            yield return h;
            yield return a | h;
            yield return b | h;
            yield return a | b | h;
            yield return c | h;
            yield return a | c | h;
            yield return b | c | h;
            yield return a | b | c | h;
            yield return d | h;
            yield return a | d | h;
            yield return b | d | h;
            yield return a | b | d | h;
            yield return c | d | h;
            yield return a | c | d | h;
            yield return b | c | d | h;
            yield return a | b | c | d | h;
            yield return e | h;
            yield return a | e | h;
            yield return b | e | h;
            yield return a | b | e | h;
            yield return c | e | h;
            yield return a | c | e | h;
            yield return b | c | e | h;
            yield return a | b | c | e | h;
            yield return d | e | h;
            yield return a | d | e | h;
            yield return b | d | e | h;
            yield return a | b | d | e | h;
            yield return c | d | e | h;
            yield return a | c | d | e | h;
            yield return b | c | d | e | h;
            yield return a | b | c | d | e | h;
            yield return f | h;
            yield return a | f | h;
            yield return b | f | h;
            yield return a | b | f | h;
            yield return c | f | h;
            yield return a | c | f | h;
            yield return b | c | f | h;
            yield return a | b | c | f | h;
            yield return d | f | h;
            yield return a | d | f | h;
            yield return b | d | f | h;
            yield return a | b | d | f | h;
            yield return c | d | f | h;
            yield return a | c | d | f | h;
            yield return b | c | d | f | h;
            yield return a | b | c | d | f | h;
            yield return e | f | h;
            yield return a | e | f | h;
            yield return b | e | f | h;
            yield return a | b | e | f | h;
            yield return c | e | f | h;
            yield return a | c | e | f | h;
            yield return b | c | e | f | h;
            yield return a | b | c | e | f | h;
            yield return d | e | f | h;
            yield return a | d | e | f | h;
            yield return b | d | e | f | h;
            yield return a | b | d | e | f | h;
            yield return c | d | e | f | h;
            yield return a | c | d | e | f | h;
            yield return b | c | d | e | f | h;
            yield return a | b | c | d | e | f | h;
            yield return g | h;
            yield return a | g | h;
            yield return b | g | h;
            yield return a | b | g | h;
            yield return c | g | h;
            yield return a | c | g | h;
            yield return b | c | g | h;
            yield return a | b | c | g | h;
            yield return d | g | h;
            yield return a | d | g | h;
            yield return b | d | g | h;
            yield return a | b | d | g | h;
            yield return c | d | g | h;
            yield return a | c | d | g | h;
            yield return b | c | d | g | h;
            yield return a | b | c | d | g | h;
            yield return e | g | h;
            yield return a | e | g | h;
            yield return b | e | g | h;
            yield return a | b | e | g | h;
            yield return c | e | g | h;
            yield return a | c | e | g | h;
            yield return b | c | e | g | h;
            yield return a | b | c | e | g | h;
            yield return d | e | g | h;
            yield return a | d | e | g | h;
            yield return b | d | e | g | h;
            yield return a | b | d | e | g | h;
            yield return c | d | e | g | h;
            yield return a | c | d | e | g | h;
            yield return b | c | d | e | g | h;
            yield return a | b | c | d | e | g | h;
            yield return f | g | h;
            yield return a | f | g | h;
            yield return b | f | g | h;
            yield return a | b | f | g | h;
            yield return c | f | g | h;
            yield return a | c | f | g | h;
            yield return b | c | f | g | h;
            yield return a | b | c | f | g | h;
            yield return d | f | g | h;
            yield return a | d | f | g | h;
            yield return b | d | f | g | h;
            yield return a | b | d | f | g | h;
            yield return c | d | f | g | h;
            yield return a | c | d | f | g | h;
            yield return b | c | d | f | g | h;
            yield return a | b | c | d | f | g | h;
            yield return e | f | g | h;
            yield return a | e | f | g | h;
            yield return b | e | f | g | h;
            yield return a | b | e | f | g | h;
            yield return c | e | f | g | h;
            yield return a | c | e | f | g | h;
            yield return b | c | e | f | g | h;
            yield return a | b | c | e | f | g | h;
            yield return d | e | f | g | h;
            yield return a | d | e | f | g | h;
            yield return b | d | e | f | g | h;
            yield return a | b | d | e | f | g | h;
            yield return c | d | e | f | g | h;
            yield return a | c | d | e | f | g | h;
            yield return b | c | d | e | f | g | h;
            yield return a | b | c | d | e | f | g | h;
            yield return i;
            yield return a | i;
            yield return b | i;
            yield return a | b | i;
            yield return c | i;
            yield return a | c | i;
            yield return b | c | i;
            yield return a | b | c | i;
            yield return d | i;
            yield return a | d | i;
            yield return b | d | i;
            yield return a | b | d | i;
            yield return c | d | i;
            yield return a | c | d | i;
            yield return b | c | d | i;
            yield return a | b | c | d | i;
            yield return e | i;
            yield return a | e | i;
            yield return b | e | i;
            yield return a | b | e | i;
            yield return c | e | i;
            yield return a | c | e | i;
            yield return b | c | e | i;
            yield return a | b | c | e | i;
            yield return d | e | i;
            yield return a | d | e | i;
            yield return b | d | e | i;
            yield return a | b | d | e | i;
            yield return c | d | e | i;
            yield return a | c | d | e | i;
            yield return b | c | d | e | i;
            yield return a | b | c | d | e | i;
            yield return f | i;
            yield return a | f | i;
            yield return b | f | i;
            yield return a | b | f | i;
            yield return c | f | i;
            yield return a | c | f | i;
            yield return b | c | f | i;
            yield return a | b | c | f | i;
            yield return d | f | i;
            yield return a | d | f | i;
            yield return b | d | f | i;
            yield return a | b | d | f | i;
            yield return c | d | f | i;
            yield return a | c | d | f | i;
            yield return b | c | d | f | i;
            yield return a | b | c | d | f | i;
            yield return e | f | i;
            yield return a | e | f | i;
            yield return b | e | f | i;
            yield return a | b | e | f | i;
            yield return c | e | f | i;
            yield return a | c | e | f | i;
            yield return b | c | e | f | i;
            yield return a | b | c | e | f | i;
            yield return d | e | f | i;
            yield return a | d | e | f | i;
            yield return b | d | e | f | i;
            yield return a | b | d | e | f | i;
            yield return c | d | e | f | i;
            yield return a | c | d | e | f | i;
            yield return b | c | d | e | f | i;
            yield return a | b | c | d | e | f | i;
            yield return g | i;
            yield return a | g | i;
            yield return b | g | i;
            yield return a | b | g | i;
            yield return c | g | i;
            yield return a | c | g | i;
            yield return b | c | g | i;
            yield return a | b | c | g | i;
            yield return d | g | i;
            yield return a | d | g | i;
            yield return b | d | g | i;
            yield return a | b | d | g | i;
            yield return c | d | g | i;
            yield return a | c | d | g | i;
            yield return b | c | d | g | i;
            yield return a | b | c | d | g | i;
            yield return e | g | i;
            yield return a | e | g | i;
            yield return b | e | g | i;
            yield return a | b | e | g | i;
            yield return c | e | g | i;
            yield return a | c | e | g | i;
            yield return b | c | e | g | i;
            yield return a | b | c | e | g | i;
            yield return d | e | g | i;
            yield return a | d | e | g | i;
            yield return b | d | e | g | i;
            yield return a | b | d | e | g | i;
            yield return c | d | e | g | i;
            yield return a | c | d | e | g | i;
            yield return b | c | d | e | g | i;
            yield return a | b | c | d | e | g | i;
            yield return f | g | i;
            yield return a | f | g | i;
            yield return b | f | g | i;
            yield return a | b | f | g | i;
            yield return c | f | g | i;
            yield return a | c | f | g | i;
            yield return b | c | f | g | i;
            yield return a | b | c | f | g | i;
            yield return d | f | g | i;
            yield return a | d | f | g | i;
            yield return b | d | f | g | i;
            yield return a | b | d | f | g | i;
            yield return c | d | f | g | i;
            yield return a | c | d | f | g | i;
            yield return b | c | d | f | g | i;
            yield return a | b | c | d | f | g | i;
            yield return e | f | g | i;
            yield return a | e | f | g | i;
            yield return b | e | f | g | i;
            yield return a | b | e | f | g | i;
            yield return c | e | f | g | i;
            yield return a | c | e | f | g | i;
            yield return b | c | e | f | g | i;
            yield return a | b | c | e | f | g | i;
            yield return d | e | f | g | i;
            yield return a | d | e | f | g | i;
            yield return b | d | e | f | g | i;
            yield return a | b | d | e | f | g | i;
            yield return c | d | e | f | g | i;
            yield return a | c | d | e | f | g | i;
            yield return b | c | d | e | f | g | i;
            yield return a | b | c | d | e | f | g | i;
            yield return h | i;
            yield return a | h | i;
            yield return b | h | i;
            yield return a | b | h | i;
            yield return c | h | i;
            yield return a | c | h | i;
            yield return b | c | h | i;
            yield return a | b | c | h | i;
            yield return d | h | i;
            yield return a | d | h | i;
            yield return b | d | h | i;
            yield return a | b | d | h | i;
            yield return c | d | h | i;
            yield return a | c | d | h | i;
            yield return b | c | d | h | i;
            yield return a | b | c | d | h | i;
            yield return e | h | i;
            yield return a | e | h | i;
            yield return b | e | h | i;
            yield return a | b | e | h | i;
            yield return c | e | h | i;
            yield return a | c | e | h | i;
            yield return b | c | e | h | i;
            yield return a | b | c | e | h | i;
            yield return d | e | h | i;
            yield return a | d | e | h | i;
            yield return b | d | e | h | i;
            yield return a | b | d | e | h | i;
            yield return c | d | e | h | i;
            yield return a | c | d | e | h | i;
            yield return b | c | d | e | h | i;
            yield return a | b | c | d | e | h | i;
            yield return f | h | i;
            yield return a | f | h | i;
            yield return b | f | h | i;
            yield return a | b | f | h | i;
            yield return c | f | h | i;
            yield return a | c | f | h | i;
            yield return b | c | f | h | i;
            yield return a | b | c | f | h | i;
            yield return d | f | h | i;
            yield return a | d | f | h | i;
            yield return b | d | f | h | i;
            yield return a | b | d | f | h | i;
            yield return c | d | f | h | i;
            yield return a | c | d | f | h | i;
            yield return b | c | d | f | h | i;
            yield return a | b | c | d | f | h | i;
            yield return e | f | h | i;
            yield return a | e | f | h | i;
            yield return b | e | f | h | i;
            yield return a | b | e | f | h | i;
            yield return c | e | f | h | i;
            yield return a | c | e | f | h | i;
            yield return b | c | e | f | h | i;
            yield return a | b | c | e | f | h | i;
            yield return d | e | f | h | i;
            yield return a | d | e | f | h | i;
            yield return b | d | e | f | h | i;
            yield return a | b | d | e | f | h | i;
            yield return c | d | e | f | h | i;
            yield return a | c | d | e | f | h | i;
            yield return b | c | d | e | f | h | i;
            yield return a | b | c | d | e | f | h | i;
            yield return g | h | i;
            yield return a | g | h | i;
            yield return b | g | h | i;
            yield return a | b | g | h | i;
            yield return c | g | h | i;
            yield return a | c | g | h | i;
            yield return b | c | g | h | i;
            yield return a | b | c | g | h | i;
            yield return d | g | h | i;
            yield return a | d | g | h | i;
            yield return b | d | g | h | i;
            yield return a | b | d | g | h | i;
            yield return c | d | g | h | i;
            yield return a | c | d | g | h | i;
            yield return b | c | d | g | h | i;
            yield return a | b | c | d | g | h | i;
            yield return e | g | h | i;
            yield return a | e | g | h | i;
            yield return b | e | g | h | i;
            yield return a | b | e | g | h | i;
            yield return c | e | g | h | i;
            yield return a | c | e | g | h | i;
            yield return b | c | e | g | h | i;
            yield return a | b | c | e | g | h | i;
            yield return d | e | g | h | i;
            yield return a | d | e | g | h | i;
            yield return b | d | e | g | h | i;
            yield return a | b | d | e | g | h | i;
            yield return c | d | e | g | h | i;
            yield return a | c | d | e | g | h | i;
            yield return b | c | d | e | g | h | i;
            yield return a | b | c | d | e | g | h | i;
            yield return f | g | h | i;
            yield return a | f | g | h | i;
            yield return b | f | g | h | i;
            yield return a | b | f | g | h | i;
            yield return c | f | g | h | i;
            yield return a | c | f | g | h | i;
            yield return b | c | f | g | h | i;
            yield return a | b | c | f | g | h | i;
            yield return d | f | g | h | i;
            yield return a | d | f | g | h | i;
            yield return b | d | f | g | h | i;
            yield return a | b | d | f | g | h | i;
            yield return c | d | f | g | h | i;
            yield return a | c | d | f | g | h | i;
            yield return b | c | d | f | g | h | i;
            yield return a | b | c | d | f | g | h | i;
            yield return e | f | g | h | i;
            yield return a | e | f | g | h | i;
            yield return b | e | f | g | h | i;
            yield return a | b | e | f | g | h | i;
            yield return c | e | f | g | h | i;
            yield return a | c | e | f | g | h | i;
            yield return b | c | e | f | g | h | i;
            yield return a | b | c | e | f | g | h | i;
            yield return d | e | f | g | h | i;
            yield return a | d | e | f | g | h | i;
            yield return b | d | e | f | g | h | i;
            yield return a | b | d | e | f | g | h | i;
            yield return c | d | e | f | g | h | i;
            yield return a | c | d | e | f | g | h | i;
            yield return b | c | d | e | f | g | h | i;
            yield return a | b | c | d | e | f | g | h | i;
            yield return j;
            yield return a | j;
            yield return b | j;
            yield return a | b | j;
            yield return c | j;
            yield return a | c | j;
            yield return b | c | j;
            yield return a | b | c | j;
            yield return d | j;
            yield return a | d | j;
            yield return b | d | j;
            yield return a | b | d | j;
            yield return c | d | j;
            yield return a | c | d | j;
            yield return b | c | d | j;
            yield return a | b | c | d | j;
            yield return e | j;
            yield return a | e | j;
            yield return b | e | j;
            yield return a | b | e | j;
            yield return c | e | j;
            yield return a | c | e | j;
            yield return b | c | e | j;
            yield return a | b | c | e | j;
            yield return d | e | j;
            yield return a | d | e | j;
            yield return b | d | e | j;
            yield return a | b | d | e | j;
            yield return c | d | e | j;
            yield return a | c | d | e | j;
            yield return b | c | d | e | j;
            yield return a | b | c | d | e | j;
            yield return f | j;
            yield return a | f | j;
            yield return b | f | j;
            yield return a | b | f | j;
            yield return c | f | j;
            yield return a | c | f | j;
            yield return b | c | f | j;
            yield return a | b | c | f | j;
            yield return d | f | j;
            yield return a | d | f | j;
            yield return b | d | f | j;
            yield return a | b | d | f | j;
            yield return c | d | f | j;
            yield return a | c | d | f | j;
            yield return b | c | d | f | j;
            yield return a | b | c | d | f | j;
            yield return e | f | j;
            yield return a | e | f | j;
            yield return b | e | f | j;
            yield return a | b | e | f | j;
            yield return c | e | f | j;
            yield return a | c | e | f | j;
            yield return b | c | e | f | j;
            yield return a | b | c | e | f | j;
            yield return d | e | f | j;
            yield return a | d | e | f | j;
            yield return b | d | e | f | j;
            yield return a | b | d | e | f | j;
            yield return c | d | e | f | j;
            yield return a | c | d | e | f | j;
            yield return b | c | d | e | f | j;
            yield return a | b | c | d | e | f | j;
            yield return g | j;
            yield return a | g | j;
            yield return b | g | j;
            yield return a | b | g | j;
            yield return c | g | j;
            yield return a | c | g | j;
            yield return b | c | g | j;
            yield return a | b | c | g | j;
            yield return d | g | j;
            yield return a | d | g | j;
            yield return b | d | g | j;
            yield return a | b | d | g | j;
            yield return c | d | g | j;
            yield return a | c | d | g | j;
            yield return b | c | d | g | j;
            yield return a | b | c | d | g | j;
            yield return e | g | j;
            yield return a | e | g | j;
            yield return b | e | g | j;
            yield return a | b | e | g | j;
            yield return c | e | g | j;
            yield return a | c | e | g | j;
            yield return b | c | e | g | j;
            yield return a | b | c | e | g | j;
            yield return d | e | g | j;
            yield return a | d | e | g | j;
            yield return b | d | e | g | j;
            yield return a | b | d | e | g | j;
            yield return c | d | e | g | j;
            yield return a | c | d | e | g | j;
            yield return b | c | d | e | g | j;
            yield return a | b | c | d | e | g | j;
            yield return f | g | j;
            yield return a | f | g | j;
            yield return b | f | g | j;
            yield return a | b | f | g | j;
            yield return c | f | g | j;
            yield return a | c | f | g | j;
            yield return b | c | f | g | j;
            yield return a | b | c | f | g | j;
            yield return d | f | g | j;
            yield return a | d | f | g | j;
            yield return b | d | f | g | j;
            yield return a | b | d | f | g | j;
            yield return c | d | f | g | j;
            yield return a | c | d | f | g | j;
            yield return b | c | d | f | g | j;
            yield return a | b | c | d | f | g | j;
            yield return e | f | g | j;
            yield return a | e | f | g | j;
            yield return b | e | f | g | j;
            yield return a | b | e | f | g | j;
            yield return c | e | f | g | j;
            yield return a | c | e | f | g | j;
            yield return b | c | e | f | g | j;
            yield return a | b | c | e | f | g | j;
            yield return d | e | f | g | j;
            yield return a | d | e | f | g | j;
            yield return b | d | e | f | g | j;
            yield return a | b | d | e | f | g | j;
            yield return c | d | e | f | g | j;
            yield return a | c | d | e | f | g | j;
            yield return b | c | d | e | f | g | j;
            yield return a | b | c | d | e | f | g | j;
            yield return h | j;
            yield return a | h | j;
            yield return b | h | j;
            yield return a | b | h | j;
            yield return c | h | j;
            yield return a | c | h | j;
            yield return b | c | h | j;
            yield return a | b | c | h | j;
            yield return d | h | j;
            yield return a | d | h | j;
            yield return b | d | h | j;
            yield return a | b | d | h | j;
            yield return c | d | h | j;
            yield return a | c | d | h | j;
            yield return b | c | d | h | j;
            yield return a | b | c | d | h | j;
            yield return e | h | j;
            yield return a | e | h | j;
            yield return b | e | h | j;
            yield return a | b | e | h | j;
            yield return c | e | h | j;
            yield return a | c | e | h | j;
            yield return b | c | e | h | j;
            yield return a | b | c | e | h | j;
            yield return d | e | h | j;
            yield return a | d | e | h | j;
            yield return b | d | e | h | j;
            yield return a | b | d | e | h | j;
            yield return c | d | e | h | j;
            yield return a | c | d | e | h | j;
            yield return b | c | d | e | h | j;
            yield return a | b | c | d | e | h | j;
            yield return f | h | j;
            yield return a | f | h | j;
            yield return b | f | h | j;
            yield return a | b | f | h | j;
            yield return c | f | h | j;
            yield return a | c | f | h | j;
            yield return b | c | f | h | j;
            yield return a | b | c | f | h | j;
            yield return d | f | h | j;
            yield return a | d | f | h | j;
            yield return b | d | f | h | j;
            yield return a | b | d | f | h | j;
            yield return c | d | f | h | j;
            yield return a | c | d | f | h | j;
            yield return b | c | d | f | h | j;
            yield return a | b | c | d | f | h | j;
            yield return e | f | h | j;
            yield return a | e | f | h | j;
            yield return b | e | f | h | j;
            yield return a | b | e | f | h | j;
            yield return c | e | f | h | j;
            yield return a | c | e | f | h | j;
            yield return b | c | e | f | h | j;
            yield return a | b | c | e | f | h | j;
            yield return d | e | f | h | j;
            yield return a | d | e | f | h | j;
            yield return b | d | e | f | h | j;
            yield return a | b | d | e | f | h | j;
            yield return c | d | e | f | h | j;
            yield return a | c | d | e | f | h | j;
            yield return b | c | d | e | f | h | j;
            yield return a | b | c | d | e | f | h | j;
            yield return g | h | j;
            yield return a | g | h | j;
            yield return b | g | h | j;
            yield return a | b | g | h | j;
            yield return c | g | h | j;
            yield return a | c | g | h | j;
            yield return b | c | g | h | j;
            yield return a | b | c | g | h | j;
            yield return d | g | h | j;
            yield return a | d | g | h | j;
            yield return b | d | g | h | j;
            yield return a | b | d | g | h | j;
            yield return c | d | g | h | j;
            yield return a | c | d | g | h | j;
            yield return b | c | d | g | h | j;
            yield return a | b | c | d | g | h | j;
            yield return e | g | h | j;
            yield return a | e | g | h | j;
            yield return b | e | g | h | j;
            yield return a | b | e | g | h | j;
            yield return c | e | g | h | j;
            yield return a | c | e | g | h | j;
            yield return b | c | e | g | h | j;
            yield return a | b | c | e | g | h | j;
            yield return d | e | g | h | j;
            yield return a | d | e | g | h | j;
            yield return b | d | e | g | h | j;
            yield return a | b | d | e | g | h | j;
            yield return c | d | e | g | h | j;
            yield return a | c | d | e | g | h | j;
            yield return b | c | d | e | g | h | j;
            yield return a | b | c | d | e | g | h | j;
            yield return f | g | h | j;
            yield return a | f | g | h | j;
            yield return b | f | g | h | j;
            yield return a | b | f | g | h | j;
            yield return c | f | g | h | j;
            yield return a | c | f | g | h | j;
            yield return b | c | f | g | h | j;
            yield return a | b | c | f | g | h | j;
            yield return d | f | g | h | j;
            yield return a | d | f | g | h | j;
            yield return b | d | f | g | h | j;
            yield return a | b | d | f | g | h | j;
            yield return c | d | f | g | h | j;
            yield return a | c | d | f | g | h | j;
            yield return b | c | d | f | g | h | j;
            yield return a | b | c | d | f | g | h | j;
            yield return e | f | g | h | j;
            yield return a | e | f | g | h | j;
            yield return b | e | f | g | h | j;
            yield return a | b | e | f | g | h | j;
            yield return c | e | f | g | h | j;
            yield return a | c | e | f | g | h | j;
            yield return b | c | e | f | g | h | j;
            yield return a | b | c | e | f | g | h | j;
            yield return d | e | f | g | h | j;
            yield return a | d | e | f | g | h | j;
            yield return b | d | e | f | g | h | j;
            yield return a | b | d | e | f | g | h | j;
            yield return c | d | e | f | g | h | j;
            yield return a | c | d | e | f | g | h | j;
            yield return b | c | d | e | f | g | h | j;
            yield return a | b | c | d | e | f | g | h | j;
            yield return i | j;
            yield return a | i | j;
            yield return b | i | j;
            yield return a | b | i | j;
            yield return c | i | j;
            yield return a | c | i | j;
            yield return b | c | i | j;
            yield return a | b | c | i | j;
            yield return d | i | j;
            yield return a | d | i | j;
            yield return b | d | i | j;
            yield return a | b | d | i | j;
            yield return c | d | i | j;
            yield return a | c | d | i | j;
            yield return b | c | d | i | j;
            yield return a | b | c | d | i | j;
            yield return e | i | j;
            yield return a | e | i | j;
            yield return b | e | i | j;
            yield return a | b | e | i | j;
            yield return c | e | i | j;
            yield return a | c | e | i | j;
            yield return b | c | e | i | j;
            yield return a | b | c | e | i | j;
            yield return d | e | i | j;
            yield return a | d | e | i | j;
            yield return b | d | e | i | j;
            yield return a | b | d | e | i | j;
            yield return c | d | e | i | j;
            yield return a | c | d | e | i | j;
            yield return b | c | d | e | i | j;
            yield return a | b | c | d | e | i | j;
            yield return f | i | j;
            yield return a | f | i | j;
            yield return b | f | i | j;
            yield return a | b | f | i | j;
            yield return c | f | i | j;
            yield return a | c | f | i | j;
            yield return b | c | f | i | j;
            yield return a | b | c | f | i | j;
            yield return d | f | i | j;
            yield return a | d | f | i | j;
            yield return b | d | f | i | j;
            yield return a | b | d | f | i | j;
            yield return c | d | f | i | j;
            yield return a | c | d | f | i | j;
            yield return b | c | d | f | i | j;
            yield return a | b | c | d | f | i | j;
            yield return e | f | i | j;
            yield return a | e | f | i | j;
            yield return b | e | f | i | j;
            yield return a | b | e | f | i | j;
            yield return c | e | f | i | j;
            yield return a | c | e | f | i | j;
            yield return b | c | e | f | i | j;
            yield return a | b | c | e | f | i | j;
            yield return d | e | f | i | j;
            yield return a | d | e | f | i | j;
            yield return b | d | e | f | i | j;
            yield return a | b | d | e | f | i | j;
            yield return c | d | e | f | i | j;
            yield return a | c | d | e | f | i | j;
            yield return b | c | d | e | f | i | j;
            yield return a | b | c | d | e | f | i | j;
            yield return g | i | j;
            yield return a | g | i | j;
            yield return b | g | i | j;
            yield return a | b | g | i | j;
            yield return c | g | i | j;
            yield return a | c | g | i | j;
            yield return b | c | g | i | j;
            yield return a | b | c | g | i | j;
            yield return d | g | i | j;
            yield return a | d | g | i | j;
            yield return b | d | g | i | j;
            yield return a | b | d | g | i | j;
            yield return c | d | g | i | j;
            yield return a | c | d | g | i | j;
            yield return b | c | d | g | i | j;
            yield return a | b | c | d | g | i | j;
            yield return e | g | i | j;
            yield return a | e | g | i | j;
            yield return b | e | g | i | j;
            yield return a | b | e | g | i | j;
            yield return c | e | g | i | j;
            yield return a | c | e | g | i | j;
            yield return b | c | e | g | i | j;
            yield return a | b | c | e | g | i | j;
            yield return d | e | g | i | j;
            yield return a | d | e | g | i | j;
            yield return b | d | e | g | i | j;
            yield return a | b | d | e | g | i | j;
            yield return c | d | e | g | i | j;
            yield return a | c | d | e | g | i | j;
            yield return b | c | d | e | g | i | j;
            yield return a | b | c | d | e | g | i | j;
            yield return f | g | i | j;
            yield return a | f | g | i | j;
            yield return b | f | g | i | j;
            yield return a | b | f | g | i | j;
            yield return c | f | g | i | j;
            yield return a | c | f | g | i | j;
            yield return b | c | f | g | i | j;
            yield return a | b | c | f | g | i | j;
            yield return d | f | g | i | j;
            yield return a | d | f | g | i | j;
            yield return b | d | f | g | i | j;
            yield return a | b | d | f | g | i | j;
            yield return c | d | f | g | i | j;
            yield return a | c | d | f | g | i | j;
            yield return b | c | d | f | g | i | j;
            yield return a | b | c | d | f | g | i | j;
            yield return e | f | g | i | j;
            yield return a | e | f | g | i | j;
            yield return b | e | f | g | i | j;
            yield return a | b | e | f | g | i | j;
            yield return c | e | f | g | i | j;
            yield return a | c | e | f | g | i | j;
            yield return b | c | e | f | g | i | j;
            yield return a | b | c | e | f | g | i | j;
            yield return d | e | f | g | i | j;
            yield return a | d | e | f | g | i | j;
            yield return b | d | e | f | g | i | j;
            yield return a | b | d | e | f | g | i | j;
            yield return c | d | e | f | g | i | j;
            yield return a | c | d | e | f | g | i | j;
            yield return b | c | d | e | f | g | i | j;
            yield return a | b | c | d | e | f | g | i | j;
            yield return h | i | j;
            yield return a | h | i | j;
            yield return b | h | i | j;
            yield return a | b | h | i | j;
            yield return c | h | i | j;
            yield return a | c | h | i | j;
            yield return b | c | h | i | j;
            yield return a | b | c | h | i | j;
            yield return d | h | i | j;
            yield return a | d | h | i | j;
            yield return b | d | h | i | j;
            yield return a | b | d | h | i | j;
            yield return c | d | h | i | j;
            yield return a | c | d | h | i | j;
            yield return b | c | d | h | i | j;
            yield return a | b | c | d | h | i | j;
            yield return e | h | i | j;
            yield return a | e | h | i | j;
            yield return b | e | h | i | j;
            yield return a | b | e | h | i | j;
            yield return c | e | h | i | j;
            yield return a | c | e | h | i | j;
            yield return b | c | e | h | i | j;
            yield return a | b | c | e | h | i | j;
            yield return d | e | h | i | j;
            yield return a | d | e | h | i | j;
            yield return b | d | e | h | i | j;
            yield return a | b | d | e | h | i | j;
            yield return c | d | e | h | i | j;
            yield return a | c | d | e | h | i | j;
            yield return b | c | d | e | h | i | j;
            yield return a | b | c | d | e | h | i | j;
            yield return f | h | i | j;
            yield return a | f | h | i | j;
            yield return b | f | h | i | j;
            yield return a | b | f | h | i | j;
            yield return c | f | h | i | j;
            yield return a | c | f | h | i | j;
            yield return b | c | f | h | i | j;
            yield return a | b | c | f | h | i | j;
            yield return d | f | h | i | j;
            yield return a | d | f | h | i | j;
            yield return b | d | f | h | i | j;
            yield return a | b | d | f | h | i | j;
            yield return c | d | f | h | i | j;
            yield return a | c | d | f | h | i | j;
            yield return b | c | d | f | h | i | j;
            yield return a | b | c | d | f | h | i | j;
            yield return e | f | h | i | j;
            yield return a | e | f | h | i | j;
            yield return b | e | f | h | i | j;
            yield return a | b | e | f | h | i | j;
            yield return c | e | f | h | i | j;
            yield return a | c | e | f | h | i | j;
            yield return b | c | e | f | h | i | j;
            yield return a | b | c | e | f | h | i | j;
            yield return d | e | f | h | i | j;
            yield return a | d | e | f | h | i | j;
            yield return b | d | e | f | h | i | j;
            yield return a | b | d | e | f | h | i | j;
            yield return c | d | e | f | h | i | j;
            yield return a | c | d | e | f | h | i | j;
            yield return b | c | d | e | f | h | i | j;
            yield return a | b | c | d | e | f | h | i | j;
            yield return g | h | i | j;
            yield return a | g | h | i | j;
            yield return b | g | h | i | j;
            yield return a | b | g | h | i | j;
            yield return c | g | h | i | j;
            yield return a | c | g | h | i | j;
            yield return b | c | g | h | i | j;
            yield return a | b | c | g | h | i | j;
            yield return d | g | h | i | j;
            yield return a | d | g | h | i | j;
            yield return b | d | g | h | i | j;
            yield return a | b | d | g | h | i | j;
            yield return c | d | g | h | i | j;
            yield return a | c | d | g | h | i | j;
            yield return b | c | d | g | h | i | j;
            yield return a | b | c | d | g | h | i | j;
            yield return e | g | h | i | j;
            yield return a | e | g | h | i | j;
            yield return b | e | g | h | i | j;
            yield return a | b | e | g | h | i | j;
            yield return c | e | g | h | i | j;
            yield return a | c | e | g | h | i | j;
            yield return b | c | e | g | h | i | j;
            yield return a | b | c | e | g | h | i | j;
            yield return d | e | g | h | i | j;
            yield return a | d | e | g | h | i | j;
            yield return b | d | e | g | h | i | j;
            yield return a | b | d | e | g | h | i | j;
            yield return c | d | e | g | h | i | j;
            yield return a | c | d | e | g | h | i | j;
            yield return b | c | d | e | g | h | i | j;
            yield return a | b | c | d | e | g | h | i | j;
            yield return f | g | h | i | j;
            yield return a | f | g | h | i | j;
            yield return b | f | g | h | i | j;
            yield return a | b | f | g | h | i | j;
            yield return c | f | g | h | i | j;
            yield return a | c | f | g | h | i | j;
            yield return b | c | f | g | h | i | j;
            yield return a | b | c | f | g | h | i | j;
            yield return d | f | g | h | i | j;
            yield return a | d | f | g | h | i | j;
            yield return b | d | f | g | h | i | j;
            yield return a | b | d | f | g | h | i | j;
            yield return c | d | f | g | h | i | j;
            yield return a | c | d | f | g | h | i | j;
            yield return b | c | d | f | g | h | i | j;
            yield return a | b | c | d | f | g | h | i | j;
            yield return e | f | g | h | i | j;
            yield return a | e | f | g | h | i | j;
            yield return b | e | f | g | h | i | j;
            yield return a | b | e | f | g | h | i | j;
            yield return c | e | f | g | h | i | j;
            yield return a | c | e | f | g | h | i | j;
            yield return b | c | e | f | g | h | i | j;
            yield return a | b | c | e | f | g | h | i | j;
            yield return d | e | f | g | h | i | j;
            yield return a | d | e | f | g | h | i | j;
            yield return b | d | e | f | g | h | i | j;
            yield return a | b | d | e | f | g | h | i | j;
            yield return c | d | e | f | g | h | i | j;
            yield return a | c | d | e | f | g | h | i | j;
            yield return b | c | d | e | f | g | h | i | j;
            yield return a | b | c | d | e | f | g | h | i | j;
        }

        #endregion
    }
}