//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xunit {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xunit.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only be applied to enum-typed parameters.
        /// </summary>
        internal static string AllFlagsOnlyOnEnums {
            get {
                return ResourceManager.GetString("AllFlagsOnlyOnEnums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only be applied to flags enums.
        /// </summary>
        internal static string AllFlagsOnlyOnFlagsEnums {
            get {
                return ResourceManager.GetString("AllFlagsOnlyOnFlagsEnums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must contain at least one element..
        /// </summary>
        internal static string Argument_EmptyArray {
            get {
                return ResourceManager.GetString("Argument_EmptyArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be an empty string (&quot;&quot;) or start with the null character..
        /// </summary>
        internal static string Argument_EmptyString {
            get {
                return ResourceManager.GetString("Argument_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot contain a null (Nothing in Visual Basic) element..
        /// </summary>
        internal static string Argument_NullElement {
            get {
                return ResourceManager.GetString("Argument_NullElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &quot;{0}&quot; cannot consist entirely of white space characters..
        /// </summary>
        internal static string Argument_Whitespace {
            get {
                return ResourceManager.GetString("Argument_Whitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot generate values for type {0}.
        /// </summary>
        internal static string CannotGenerateValues {
            get {
                return ResourceManager.GetString("CannotGenerateValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one method in a test class may be decorated with {0}.
        /// </summary>
        internal static string DefaultsAttributeSingleMethod {
            get {
                return ResourceManager.GetString("DefaultsAttributeSingleMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method decorated with {0} must be static..
        /// </summary>
        internal static string DefaultsMethodNonStatic {
            get {
                return ResourceManager.GetString("DefaultsMethodNonStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method decorated with {0} does not have the correct signature of &lt; void MethodName({1} arg) &gt;.
        /// </summary>
        internal static string DefaultsMethodSignature {
            get {
                return ResourceManager.GetString("DefaultsMethodSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot auto-generate values for a flag enum - it is too likely to result in an explosion of combinations.
        /// </summary>
        internal static string FlagEnumAutoGen {
            get {
                return ResourceManager.GetString("FlagEnumAutoGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred. Please contact customer support..
        /// </summary>
        internal static string InternalExceptionMessage {
            get {
                return ResourceManager.GetString("InternalExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an instance of the {0} service..
        /// </summary>
        internal static string ServiceMissing {
            get {
                return ResourceManager.GetString("ServiceMissing", resourceCulture);
            }
        }
    }
}
