//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xunit {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xunit.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only be applied to enum-typed parameters.
        /// </summary>
        internal static string AllFlagsOnlyOnEnums {
            get {
                return ResourceManager.GetString("AllFlagsOnlyOnEnums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only be applied to flags enums.
        /// </summary>
        internal static string AllFlagsOnlyOnFlagsEnums {
            get {
                return ResourceManager.GetString("AllFlagsOnlyOnFlagsEnums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must contain at least one element..
        /// </summary>
        internal static string Argument_EmptyArray {
            get {
                return ResourceManager.GetString("Argument_EmptyArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be an empty string (&quot;&quot;) or start with the null character..
        /// </summary>
        internal static string Argument_EmptyString {
            get {
                return ResourceManager.GetString("Argument_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot contain a null (Nothing in Visual Basic) element..
        /// </summary>
        internal static string Argument_NullElement {
            get {
                return ResourceManager.GetString("Argument_NullElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &quot;{0}&quot; cannot consist entirely of white space characters..
        /// </summary>
        internal static string Argument_Whitespace {
            get {
                return ResourceManager.GetString("Argument_Whitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot generate values for type {0}.
        /// </summary>
        internal static string CannotGenerateValues {
            get {
                return ResourceManager.GetString("CannotGenerateValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one method in a test class may be decorated with {0}.
        /// </summary>
        internal static string DefaultsAttributeSingleMethod {
            get {
                return ResourceManager.GetString("DefaultsAttributeSingleMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method decorated with {0} must be static..
        /// </summary>
        internal static string DefaultsMethodNonStatic {
            get {
                return ResourceManager.GetString("DefaultsMethodNonStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method decorated with {0} does not have the correct signature of &lt; void MethodName({1} arg) &gt;.
        /// </summary>
        internal static string DefaultsMethodSignature {
            get {
                return ResourceManager.GetString("DefaultsMethodSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot auto-generate values for a flag enum - it is too likely to result in an explosion of combinations.
        /// </summary>
        internal static string FlagEnumAutoGen {
            get {
                return ResourceManager.GetString("FlagEnumAutoGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred. Please contact customer support..
        /// </summary>
        internal static string InternalExceptionMessage {
            get {
                return ResourceManager.GetString("InternalExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found more than one static method or property called {0} on the class {1} that satisfies the signature required..
        /// </summary>
        internal static string MemberMoreThanOne {
            get {
                return ResourceManager.GetString("MemberMoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a static method or property called {0} on the class {1} that satisfies the signature required..
        /// </summary>
        internal static string MemberNoMethodOrProp {
            get {
                return ResourceManager.GetString("MemberNoMethodOrProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double values cannot be applied to float/Single parameters as there may be a loss of precision.
        /// </summary>
        internal static string RangeDoubleNotApplicableToSingle {
            get {
                return ResourceManager.GetString("RangeDoubleNotApplicableToSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating point values cannot be applied to a parameter taking an integer type due to rounding. Use the long or ulong overload instead..
        /// </summary>
        internal static string RangeFloatingNotApplicableToInteger {
            get {
                return ResourceManager.GetString("RangeFloatingNotApplicableToInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating point values cannot be applied to a parameter taking a decimal as there may be precision loss since single/double do not represent the same set as decimal.
        /// </summary>
        internal static string RangeFloatingPointNotApplicableToDecimal {
            get {
                return ResourceManager.GetString("RangeFloatingPointNotApplicableToDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lower bound specified is out of the range of the {0} type..
        /// </summary>
        internal static string RangeLowerBoundOutOfRange {
            get {
                return ResourceManager.GetString("RangeLowerBoundOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be used on a parameter that is not a built-in numeric type.
        /// </summary>
        internal static string RangeNotNumericType {
            get {
                return ResourceManager.GetString("RangeNotNumericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be strictly positive.
        /// </summary>
        internal static string RangeStepMustBePositive {
            get {
                return ResourceManager.GetString("RangeStepMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The step size specified is out of the range of the {0} type..
        /// </summary>
        internal static string RangeStepOutOfRange {
            get {
                return ResourceManager.GetString("RangeStepOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upper bound specified is out of the range of the {0} type..
        /// </summary>
        internal static string RangeUpperBoundOutOfRange {
            get {
                return ResourceManager.GetString("RangeUpperBoundOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an instance of the {0} service..
        /// </summary>
        internal static string ServiceMissing {
            get {
                return ResourceManager.GetString("ServiceMissing", resourceCulture);
            }
        }
    }
}
