steps:
- powershell: azure-pipelines/Merge-CodeCoverage.ps1 -Path '$(Build.ArtifactStagingDirectory)\coverageResults-Linux' -OutputFile coveragereport/merged.cobertura.xml -Format Cobertura -Verbose
  displayName: ⚙ Merge coverage
- task: PublishCodeCoverageResults@1
  displayName: 📢 Publish code coverage results to Azure DevOps
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: coveragereport/merged.cobertura.xml
    failIfCoverageEmpty: true
