steps:
- powershell: |
    dotnet tool install --tool-path obj dotnet-reportgenerator-globaltool --version 4.8.5 --configfile azure-pipelines/justnugetorg.nuget.config
    Write-Host "Substituting {reporoot} with $(System.DefaultWorkingDirectory)"
    $reports = Get-ChildItem -Recurse "$env:BUILD_ARTIFACTSTAGINGDIRECTORY/coverage.*.cobertura.xml"
    $reports |% {
        $content = Get-Content -Path $_ |% { $_.Replace("{reporoot}", "$(System.DefaultWorkingDirectory)") }
        Set-Content -Path $_ -Value $content -Encoding UTF8
    }
    $Inputs = [string]::join(';', ($reports |% { Resolve-Path -relative $_ }))
    obj/reportgenerator -reports:"$Inputs" -targetdir:coveragereport -reporttypes:Cobertura
  displayName: Merge coverage
- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage results to Azure DevOps
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: 'coveragereport/Cobertura.xml'
    failIfCoverageEmpty: true
